development:
  database: trade_analysis_dev
  host: localhost
  allow_dynamic_fields: false
    
test:
  database: trade_analysis_test
  host: localhost
  allow_dynamic_fields: false

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>