development:
  host: localhost
  database: trade_analysis_dev
  allow_dynamic_fields: false

test:
  host: localhost
  database: trade_analysis_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>